
name: Test and Deploy

on: 
  push:
    branches:
      - main

jobs: 
  hello:
    name: Say the thing
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world!"
        
