name: Test and Deploy

on: 
  workflow_dispatch:
  push:
    branches: 
      - main 


jobs: 

  hello:
    name: Say the thing
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world!"
  
  test:
    name: Run application tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'nc_news_test'

      - name: set env variables - db names nc_news_test 
        run: echo "PGDATABASE=postgresql://postgres@localhost:5432/nc_news_test" >> $GITHUB_ENV
        
      - name: Run tests
        run: PGDATABASE=nc_news_test npm t

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: curl ${{ secrets.RENDER_HOOK }}
