name: Test and Deploy

on: 
  workflow_dispatch:
  push:
    branches: 
      - main 


jobs: 

  hello:
    name: Say the thing
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world!"
  
  test:
    name: Run application tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4


      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18


      - name: Install dependencies
        run: npm ci

      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'nc_news_test'

      - name: set env variables - db names nc_news_test 
        run: echo "DATABASE_URL==PGDATABASE=nc_news_test node listen.js" >> $GITHUB_ENV
        
      - name: Run tests
        run: PGDATABASE=nc_news_test PGUSER=test_user PGPASSWORD=test_password npm t

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: curl ${{ secrets.RENDER_HOOK }}
